### ISSUE TITLE
Embed tree into another component

### ISSUE THREAD

**Issue by wa1vy** [jpb12/tree-viewer#6]
Hello! Thank you for the amazing work done! I am coding a web app tool for IoT Monitoring and would like to implement your tree viewer solution into one of the pages. I got stuck while trying to render it inside one of the React components, not in the whole window scale. And the second mini-issue is to understand how to merge webpack.config-s safely. I would really appreciate you for some advice. Thank you in advance!

**Comment by jpb12** [comment]
This repository is just a demo. Take a look at the [docs](https://github.com/jpb12/react-tree-graph) and [examples](https://jpb12.github.io/react-tree-graph/) on the library and raise an issue there if necessary.
